{{- if .Values.podAutoScaler.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Release.Name }}
spec:
  minReplicas: {{ .Values.podAutoScaler.minReplicas }}
  maxReplicas:  {{ .Values.podAutoScaler.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: {{ .Values.podAutoScaler.resource.averageUtilization }}
        type: Utilization
    type: Resource
{{- end }}
