{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}
spec:
  ingressClassName: "nginx"
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .name }}
    http:
      paths:
      - path: {{ default "/" .path }}
        backend:
          service:
            name: {{ $.Release.Name }}
            port:
              number: 8050
        pathType: ImplementationSpecific
  {{- end }}
  tls:
{{- range .Values.ingress.hosts }}
  - hosts:
{{- if .tls }}
    - {{ .name }}
    secretName: {{ .tlsSecret }}
{{- end }}
{{- end }}
{{- end }}
