apiVersion: v1
data:
  logging.yaml: |
    version: 1
    disable_existing_loggers: False
    formatters:
        simple:
            format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    handlers:
        console:
            class: logging.StreamHandler
            formatter: simple
    root:
        level: {{ .Values.config.log.level }}
        handlers: [console]
  LOG_CFG: logging.yaml
  OCEAN_PROVIDER_URL: {{ .Values.config.oceanProviderUrl }}
  OCEAN_PROVIDER_WORKERS: {{ .Values.config.oceanProviderWorkers | quote }}
  OCEAN_PROVIDER_TIMEOUT: {{ .Values.config.oceanProviderTimeout | quote }}
  OPERATOR_SERVICE_URL: {{ .Values.config.operatorServiceUrl }}
  AQUARIUS_URL: {{ .Values.config.aquariusUrl }}
  RBAC_SERVER_URL: {{ .Values.config.rbacUrl | quote }}
  PROVIDER_MANAGEMENT_URL: {{ .Values.config.providerManagementUrl | quote }}
  REQUEST_RETRIES: {{ .Values.config.requestRetries | quote }}
  AUTHORIZED_DECRYPTERS: {{ .Values.config.authorizedDecrypters | quote }}
  ALLOW_NON_PUBLIC_IP: {{ .Values.config.allowNonPublicIp | quote }}
  PROVIDER_FEE_TOKEN: {{ .Values.config.providerFeeToken | quote }}
kind: ConfigMap
metadata:
  annotations:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-config
