apiVersion: v1
data:
  {{- if .Values.config.aws.enabled }}
  AWS_REGION: {{ .Values.config.aws.region }}
  AWS_BUCKET_OUTPUT: {{ .Values.config.aws.bucket.output }}
  AWS_BUCKET_ADMINLOGS: {{ .Values.config.aws.bucket.adminlogs }}
  {{- end }}
  {{- if .Values.config.ipfs.enabled }}
  IPFS_OUTPUT: {{ .Values.config.ipfs.output }}
  IPFS_ADMINLOGS: {{ .Values.config.ipfs.adminlogs }}
  IPFS_OUTPUT_PREFIX: {{ .Values.config.ipfs.outputPrefix }}
  IPFS_ADMINLOGS_PREFIX: {{ .Values.config.ipfs.adminlogsPrefix }}
  IPFS_EXPIRY_TIME: {{ .Values.config.ipfs.expiryTime | quote }}
  {{- end }}
  STORAGE_CLASS: {{ .Values.config.storageClass }}
  POD_CONFIGURATION_CONTAINER: {{ .Values.config.pod.configurationContainer }}
  POD_PUBLISH_CONTAINER: {{ .Values.config.pod.publishContainer }}
  LOG_LEVEL: {{ .Values.config.log.level }}
  SERVICE_ACCOUNT: {{ .Values.config.serviceAccount }}
  MAX_JOB_DURATION: {{ .Values.config.maxJobDuration | quote  }}
  ENV_N_CPU: {{ .Values.config.env.nCpu | quote  }}
  ENV_CPU_TYPE: {{ .Values.config.env.cpuType | quote  }}
  ENV_GPU_RAM: {{ .Values.config.env.gpuRam | quote  }}
  ENV_GPU_TYPE: {{ .Values.config.env.gpuType | quote  }}
  ENV_RAM_GB: {{ .Values.config.env.ramGB | quote  }}
  ENV_DISK_GB: {{ .Values.config.env.diskGB | quote  }}
  ENV_PRICE_MINUTE: {{ .Values.config.env.priceMinute | quote  }}
  ENV_DESCRIPTION: {{ .Values.config.env.description | quote  }}
  ENV_STORAGE_EXPIRY: {{ .Values.config.env.storageExpiry | quote  }}
kind: ConfigMap
metadata:
  annotations:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-config
