## namespace
namespace: ocean-compute

## market image version
image:
  repository: public.ecr.aws/acentrik/oceanprotocol/operator-engine
  tag: 3.1.0
  ## Specify a imagePullPolicy
  pullPolicy: Always

## Set desired pod ReplicaSet
replica: 1

## Enable/Disable Kubernetes Secrets Store CSI Driver. Currently only support AWS provider.
## ref: https://secrets-store-csi-driver.sigs.k8s.io
## ref: https://github.com/aws/secrets-store-csi-driver-provider-aws
secretstore:
  enabled: true
  provider: aws

## Secret relevant values or keys, depends on secretstore flag
secret:
  postgres:
    db:
      postgresdb
      #objectName: parameter name
      #objectType: "secretsmanager" or "ssmparameter"
    user: postgresadmin
    password: changeme
    host: postgresql.ocean-operator.svc.cluster.local
    port: "5432"
  operatorPrivateKey: ""
  # aws:
  #   accessKeyId:
  #    objectName: /prod/acentrik/operator/aws-access-key-id
  #    objectType: ssmparameter
  #   secretAccessKey: changeme
  #    objectName: /prod/acentrik/operator/aws-secret-access-key
  #    objectType: ssmparameter
  ipfs:
    apiKey: false
    apiClient: false

## ConfigMap relevant values
config:
  aws:
    enabled: false
    region: ap-southeast-1
    bucket:
      output: compute-output
      adminlogs: compute-logs
  ipfs:
    enabled: true
    output: <IPFS CLUSTER PROXY API URL>
    adminlogs: <IPFS CLUSTER PROXY API URL>
    outputPrefix: <IPFS Gateway URL>
    adminlogsPrefix: <IPFS Gateway URL>
    ## expiry time must be in hour (h) or minutes (m) unit.
    ## Default 60 days = 1440 hours
    expiryTime: "1440h"
  storageClass: standard
  pod:
    configurationContainer: public.ecr.aws/acentrik/oceanprotocol/pod-configuration:new_timesout-1000
    publishContainer: public.ecr.aws/acentrik/oceanprotocol/pod-publishing:v4main
  log:
    level: INFO
  debug:
    noCleanup: false
  serviceAccount: default
  priceMinute: ""
  maxJobDuration: "900"
  env:
    nCpu: "1"
    cpuType: ""
    gpuRam: "0"
    gpuType: "0"
    ramGB: "1"
    diskGB: "3"
    priceMinute: "0"
    description: ""
    storageExpiry: "0"

## Configure pod resources
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 96Mi

storageclass:
  enabled: false
  name: standard
  reclaimPolicy: Delete
  ## AWS provisioner
  #  provisioner: kubernetes.io/aws-ebs
  #  parameters:
  #  fsType: ext4
  #  type: gp2
  #  encrypted: "true"
  #  allowedTopologies:
  #  enabled: true
  #  matchLabelExpressions:
  #  - key: failure-domain.beta.kubernetes.io/zone
  #    values:
  #  - ap-southeast-1b

  ## Azure provisioner
  #  provisioner: kubernetes.io/azure-disk
  #  parameters:
  #  kind: Managed
  #  storageaccounttype: StandardSSD_LRS
